import { ApiProperty, ApiPropertyOptional, OmitType, PartialType } from '@nestjs/swagger';
import { Transform, Type } from 'class-transformer';
import { IsBoolean, IsEnum, IsInt, IsNumber, IsOptional, IsPositive, IsUUID, Max, Min, ValidateIf } from 'class-validator';
import { AccountSummaryDto } from '../../accounts/dto/account.dto.js';
import { CategorySummaryDto } from '../../categories/dto/category.dto.js';
import { IsDateOnly, IsSafeText } from '../../common/validation/decorators.js';
import { RecurrenceFrequency, TransactionType } from '../../generated/prisma/client.js';

export class CreateRecurringDto {
  @ApiProperty({ example: 'Aluguel', maxLength: 120 })
  @IsSafeText({ maxLength: 120 })
  description: string;

  @ApiProperty({ example: 1800 })
  @IsNumber({ maxDecimalPlaces: 2, allowNaN: false, allowInfinity: false })
  @IsPositive()
  @Max(999_999_999_999.99)
  amount: number;

  @ApiProperty({ enum: TransactionType, description: 'Transfer rules are always EXPENSE (money leaves accountId)' })
  @IsEnum(TransactionType)
  type: TransactionType;

  @ApiProperty({ enum: RecurrenceFrequency, example: RecurrenceFrequency.MONTHLY })
  @IsEnum(RecurrenceFrequency)
  frequency: RecurrenceFrequency;

  @ApiPropertyOptional({ format: 'uuid', description: 'Income/expense rules. Exactly one of categoryId or toAccountId.' })
  @ValidateIf((o: CreateRecurringDto) => !o.toAccountId)
  @IsUUID()
  categoryId?: string;

  @ApiPropertyOptional({
    format: 'uuid',
    description: 'Transfer rules (e.g. a monthly contribution to an investment): generates transfers into this account',
  })
  @IsOptional()
  @IsUUID()
  toAccountId?: string;

  @ApiPropertyOptional({ format: 'uuid', description: 'Defaults to the oldest active account' })
  @IsOptional()
  @IsUUID()
  accountId?: string;

  @ApiProperty({ example: '2026-10-10', description: 'First occurrence; later ones keep its day' })
  @IsDateOnly()
  startDate: string;

  @ApiPropertyOptional({ example: '2027-10-10', description: 'Last possible occurrence' })
  @IsOptional()
  @IsDateOnly()
  endDate?: string;

  @ApiPropertyOptional({ maxLength: 500 })
  @IsOptional()
  @IsSafeText({ maxLength: 500, multiline: true, optional: true })
  notes?: string;
}

/** Changes apply to future occurrences only; schedule (start/frequency) is fixed. */
export class UpdateRecurringDto extends PartialType(
  OmitType(CreateRecurringDto, ['startDate', 'frequency', 'type', 'toAccountId']),
) {
  @ApiPropertyOptional({ description: 'Pause or resume the rule' })
  @IsOptional()
  @IsBoolean()
  active?: boolean;
}

export class UpcomingQueryDto {
  @ApiPropertyOptional({ example: 30, minimum: 1, maximum: 366, default: 30 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(366)
  days: number = 30;
}

export class RecurringResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty({ example: 'Aluguel' })
  description: string;

  @ApiProperty({ example: '1800.00' })
  amount: string;

  @ApiProperty({ enum: TransactionType })
  type: TransactionType;

  @ApiProperty({ enum: RecurrenceFrequency })
  frequency: RecurrenceFrequency;

  @ApiProperty({ type: CategorySummaryDto, nullable: true, description: 'Null for transfer rules' })
  category: CategorySummaryDto | null;

  @ApiProperty({ type: AccountSummaryDto })
  account: AccountSummaryDto;

  @ApiProperty({ type: AccountSummaryDto, nullable: true, description: 'Destination of a transfer rule' })
  toAccount: AccountSummaryDto | null;

  @ApiProperty({ example: '2026-01-10' })
  startDate: string;

  @ApiProperty({ example: null, nullable: true, type: String })
  endDate: string | null;

  @ApiProperty({ example: '2026-11-10', nullable: true, type: String, description: 'Next occurrence not yet created' })
  nextDate: string | null;

  @ApiProperty()
  active: boolean;

  @ApiProperty({ nullable: true, type: String })
  notes: string | null;

  @ApiProperty({ example: 9, description: 'Transactions (or transfers) already generated by this rule' })
  generatedCount: number;
}

export class UpcomingOccurrenceDto {
  @ApiProperty()
  ruleId: string;

  @ApiProperty({ example: 'Aluguel' })
  description: string;

  @ApiProperty({ example: '1800.00' })
  amount: string;

  @ApiProperty({ enum: TransactionType })
  type: TransactionType;

  @ApiProperty({ example: '2026-11-10' })
  date: string;

  @ApiProperty({ type: CategorySummaryDto, nullable: true })
  category: CategorySummaryDto | null;

  @ApiProperty({ type: AccountSummaryDto, nullable: true, description: 'Set for transfer rules' })
  toAccount: AccountSummaryDto | null;
}

export class MoveToInvestmentDto {
  @ApiProperty({ format: 'uuid', description: 'Investment that receives the contributions from now on' })
  @IsUUID()
  investmentId: string;

  @ApiPropertyOptional({
    default: false,
    description: 'Also turn the expenses this rule already generated into contributions (transfers)',
  })
  @IsOptional()
  @IsBoolean()
  convertPast?: boolean;
}

export class ListRecurringQueryDto {
  @ApiPropertyOptional({ description: 'Include paused rules', default: true })
  @IsOptional()
  @Transform(({ value }) => value === true || value === 'true')
  @IsBoolean()
  includeInactive?: boolean;
}
